name: tr_ton_wallet_service
description: Tron Energy Wallet - TON blockchain library
version: 1.1.0
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - example

# Add regular dependencies here.
dependencies:
  blockchain_utils: ^6.0.0
  http: ^1.6.0
  meta: ^1.17.0
  ton_dart: ^2.2.0
  tr_logger:
    git:
      url: https://github.com/Trenergy-wallet/tr_logger.git
      ref: v1.0.0

dev_dependencies:
  very_good_analysis: ^10.2.0

topics:
  - wallet
  - blockchain
  - ton
